# Generated by Django 3.0.8 on 2020-07-07 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_auto_20200707_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 9, 2, 41, 467304, tzinfo=utc)),
        ),
    ]
