# Generated by Django 3.0.8 on 2020-07-07 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_auto_20200707_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 16, 40, 48, 530876, tzinfo=utc)),
        ),
    ]
