# Generated by Django 3.0.8 on 2020-07-08 20:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_auto_20200708_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 20, 50, 0, 220383, tzinfo=utc)),
        ),
    ]
